config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'projects#index'
  resources :projects do
    resources :tasks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  validates :name, :summary, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # has_and_belongs_to_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [ :show, :edit, :update, :destroy]


  def index
    @projects = Project.all
  end

  def show

  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.start_date = Time.now.strftime("%d/%m/%Y")
    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def edit

  end

  def update

    if @project.update_attributes(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy

    @project.destroy
    redirect_to projects_path, success: 'Project was success deleted'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :summary)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    
    redirect_to project_path(@project)
  end

  def update
    if @project.update_attributes(task_params)
      redirect_to project_path(@project), success: 'Task was success updated'
    else
      render :edit, danger: 'Task was not updated'
    end
  end



  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to project_path(@project)
  end

  private
  def task_params
    params.require(:task).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    {
      success: "alert-success",
      error: "alert-danger",
      danger: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[name.to_sym] || name
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pavel App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <div class="header-top">
    <div class="container top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="<%= projects_path %>"> </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link" href="<%= projects_path %>">All Projects
                </a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="<%= new_project_path %>">New Project</a>
            </li>
          </ul>

          <ul class="navbar-nav pull-xs-right">
            <% if user_signed_in?  %>
              <li class="nav-item ">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item ">
                <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
              </li>
              <% end %>
              <li class="nav-item ">
                <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
              </li>
          </ul>



          </div>
        </nav>
      </div>
    </div>

    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
          <div class="alert <%= bootstrap_class_for(name) %>">
            <button class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <%= yield %>
        </div>
      </div>

    </div>
  </body>
  </html>

app/views/projects/_form.html.erb
<%= form_for @project, html: {multipart: true} do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :summary %>
      <%= f.text_area :summary, class: 'editor-summary form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit action: @project.new_record? ? 'Create' : 'Change', class: 'btn btn-info' %>
      <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
    </div>
<% end %>

app/views/projects/_project.html.erb
<div class="project">
  <div class="project-head">
    <h2><%= link_to project.name, project_path(project)  %></h2>

    <%= link_to 'Edit', edit_project_path(project) %>
    |
    <%= link_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?'} %>
    <% if project.start_date? %>
    <p>Created at: <%= project.start_date.strftime('%d/%m/%Y') %></p>
    <% end %>
  </div>
  <div class="project-summary">
    <%= project.summary %>
  </div>

</div>

app/views/projects/_task.html.erb
<div class="show-task">
  <% @project.tasks.each do |task| %>
        <div class="task-view" data-task_id="<%= task.id %>">
          <div class="">
            Title:
            <%= task.title %>
            <%= task.status %>
          </div>

          <div class="" >
            Task № <%= task.id %>:
            <%= task.description %>
           </div>

          <div class="task-edit">
            <%= link_to 'Edit', '/edit-task', class: 'edit_task', remote: true %>
            |
            <%= link_to 'Delete Task', [task.project, task],
                 method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
  <% end %>

</div>



<div class="add-task">
  <h2>Add a task:</h2>
  <%= form_with(model: [ @project, @project.tasks.build ], local: true) do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <% @mail = User.all.map do |i|  %>
    <% i.email  %>
    <% end %>

    <% @all_projects = Project.all.map do |i|  %>
    <% i.name %>
    <% end %>

    <p>  <%= form.select :email, @mail %> </p>
    <p><%= form.select :projects, @all_projects %></p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', project_path %>

</div>

app/views/projects/edit.html.erb
<h2>Edit project page</h2>
<%= render 'form' %>

app/views/projects/index.html.erb
<%= render @projects %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="project">
  <div class="task-header">
    <h2>Project name: <%= @project.name %></h2>
    <%= link_to 'Change', edit_project_path(@project) %>
    |
    <%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: 'Are you sure?'} %>
    <p><%= @project.summary %> </p>
  </div>
  <div class="task">
    Tasks:
  </div>
</div>
<div class="task-body">
  <%= render 'task' %>
</div>